# Backbone
backbone: resnet50

# Transfer loss related
deepda_loss_weight: 1
loss_type: bnm

# Optimizer related
lr: 0.001
weight_decay: 5e-4
lr_scheduler: True
lr_gamma: 0.0003
lr_decay: 0.75
momentum: 0.9

# Training related
n_epoch: 20