# Backbone
backbone: resnet50

# Transfer loss related
deepda_loss_weight: 0.5
loss_type: mmd

# Optimizer related
lr: 3e-3
weight_decay: 5e-4
lr_scheduler: True
lr_gamma: 0.0003
lr_decay: 0.75
momentum: 0.9

# Training related
n_epoch: 20